version: '3'

services:
  flask-pi:
    build:
      context: ./flask_site
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask_site:/app 
    container_name: flask_site
